version: '3.8'

services:
  pg-mon-db:
    image: postgres:15-alpine
    container_name: pg-mon-db
    environment:
      POSTGRES_DB: pg_mon
      POSTGRES_USER: pg_mon
      POSTGRES_PASSWORD: pg_mon_password123
    volumes:
      - /opt/postgresql10.4Mon:/var/lib/postgresql/data
    restart: always
    ports:
      - "54321:5432"

  pg-mon:
    build: .
    container_name: pg-mon
    ports:
      - "8000:8000"
    depends_on:
      - pg-mon-db
    restart: always
    environment:
      - APP_DB_HOST=pg-mon-db
      - APP_DB_PORT=5432
      - APP_DB_NAME=pg_mon
      - APP_DB_USER=pg_mon
      - APP_DB_PASS=pg_mon_password123
      - PYTHONUNBUFFERED=1
