version: '3.8'

services:
  pg-mon-db:
    image: postgres:15-alpine
    container_name: pg-mon-db
    environment:
      POSTGRES_DB: pgmon_db
      POSTGRES_USER: pgmon_user
      POSTGRES_PASSWORD: pgmon_password123
    volumes:
      - /opt/postgresql10.4Mon/pgdata:/var/lib/postgresql/data
    restart: always
    ports:
      - "54321:5432"

  pg-mon:
    build: .
    container_name: pg-mon
    ports:
      - "8000:8000"
    depends_on:
      - pg-mon-db
    restart: always
    environment:
      - APP_DB_HOST=pg-mon-db
      - APP_DB_PORT=5432
      - APP_DB_NAME=pgmon_db
      - APP_DB_USER=pgmon_user
      - APP_DB_PASS=pgmon_password123
      - PYTHONUNBUFFERED=1
